import pandas as pd
df = pd.read_csv("ipl data.csv")
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
top50 = df.head(50)
print(top50)
high_score = df[df['total_runs'] > 200]
print(high_score)
sorted_runs = df.sort_values(by='total_runs', ascending=False)
print(sorted_runs.head(20))
wins = df['winner'].value_counts()
print(wins)
pom = df['player_of_match'].value_counts().head(10)
print(pom)
seasonavg = df.groupby('season')['total_runs'].mean()
print(seasonavg)